sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.2

before_install:
  - npm install -g dockerfile_lint jsonlint js-yaml

script:

 # Validate Docker files
  - dockerfile_lint -r dockerfile_rules.yaml -f api/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f client/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f client/example/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f client/nagios/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f server/example/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f sensu/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f server/Dockerfile
  - dockerfile_lint -r dockerfile_rules.yaml -f uchiwa/Dockerfile

  # Validate JSON files
  - jsonlint api/conf.d/api.tmpl -q
  - jsonlint client/conf.d/rabbitmq.tmpl -q
  - jsonlint server/example/conf.d/internet-connection.json -q
  - jsonlint server/conf.d/server.tmpl -q

  # Validate Yaml files
  - js-yaml docker-compose.yml > /dev/null
  - js-yaml docker-cloud.yml > /dev/null
